hsv_filter_node:
  ros__parameters:
    use_sim_time: true
    min_h: 84
    max_h: 97
    min_s: 178
    max_s: 255
    min_v: 220
    max_v: 255

detection_to_3d_from_depth_node:
  ros__parameters:
    use_sim_time: true